---
# Variables listed here are applicable to all host groups

httpd_port: 80

time_server_1: "time.parmstrong.ca"
time_server_1_burst: "iburst"
time_server_2: "time2.parmstrong.ca"
time_server_2_burst: "iburst"

repository: https://github.com/parmstro/mywebapp.git
