---
# This playbook contains common plays that will be run on all nodes.

- name: Install chronyd
  yum: 
    name: "chrony"
    state: latest
  tags: chrony

- name: Install common dependencies
  yum: 
    name: 
     - libselinux-python
     - libsemanage-python
     - firewalld
    state: latest

- name: Configure chrony for time servers
  template: 
    src: chrony.conf.j2 
    dest: /etc/chrony.conf
  tags: chrony
  notify: restart chronyd
