---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code
  copy: 
    src: files/{{ item }} 
    dest: /var/www/html/{{ item }}
  loop:
    - index.html
    - about.html

- name: Creates the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php
