---
# We will use modules for RHEL8
- name: Install MariaDB package
  yum: 
    name: 
    - "mariadb-server"
    - "python"
    - "MySQL-python"
    state: latest
  when: ansible_distribution_major_version == "7"

- name: Install MariaDB package
  dnf: 
    name: 
    - "@mariadb:10.3/server"
    - "python3-PyMySQL"
    - "@python36"
    state: latest
  when: ansible_distribution_major_version == "8"

- name: Ensure Python3 is the default python on RHEL8 because sample app is old
  command: "alternatives --set python /usr/bin/python3"
  when: ansible_distribution_major_version == "8"
  
- name: Configure SELinux to allow mysql port {{ mysql_port }}
  seport: 
    ports: "{{ mysql_port }}"
    proto: tcp 
    setype: mysqld_port_t
    state: present

- name: Deploy the Mysql configuration file
  template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
  - restart mariadb

- name: Start MariaDB Service
  service:
    name: mariadb 
    state: started
    enabled: true

- name: Ensure firewalld has been started in order to add rules
  service: 
    name: firewalld
    state: started
    enabled: true

- name: Add firewall rules
  firewalld: 
    port: "{{ mysql_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Create Application Database
  mysql_db: 
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL host='%'"
    state: present

